### ISSUE TITLE
can you collabrate with me

### ISSUE THREAD

**Issue by Aakashpandey123** [arthurspk/guiadevbrasil#107]

**Comment by Aakashpandey123** [comment]
can you plz collabe with me bcause i am new in this.

**Comment by samuelevi87** [comment]
How can I help you? What are you trying to do?

**Comment by Nikitatagintsev** [comment]
I am new to this can u plz help my

**Comment by Nikitatagintsev** [comment]
.

**Comment by Aakashpandey123** [comment]
What is this?

**Comment by Aakashpandey123** [comment]
What do you mean?

**Comment by Nikitatagintsev** [comment]
To many words

**Comment by Aakashpandey123** [comment]
Can you send me yours whats app number

**Comment by Aakashpandey123** [comment]
So any other way except g mail to talk to you?

How can we talk

**Comment by Nikitatagintsev** [comment]
How old are u

**Comment by Aakashpandey123** [comment]
20

**Comment by Nikitatagintsev** [comment]
I’m 13

**Comment by Aakashpandey123** [comment]
Ohh good

**Comment by Nikitatagintsev** [comment]
There is a a way to contact me there is a vide o button bottom right of
your gmail Klick on it and then share type me in and sent it and we will
have a video chat.

**Comment by Aakashpandey123** [comment]
Ok, I will.
