### ISSUE TITLE
Update de sites que me ajudaram na faculdade, talvez ajudem mais alguém

### ISSUE THREAD

**Issue by DevEddi** [arthurspk/guiadevbrasil#110]
Javascript

https://momentjs.com/
https://animejs.com/
http://es6-features.org/#Constants
https://www.sencha.com/products/extjs/
https://babeljs.io/
https://angular.io/
https://docs.nestjs.com/

Mobile
https://reactnative.dev/
https://docs.expo.dev/

Java
https://www.eclipse.org/downloads/
https://www.oracle.com/java/technologies/javase/jdk12-archive-downloads.html
https://www.oracle.com/index.html
https://www.oracle.com/br/index.html
https://docs.oracle.com/javase/8/docs/
https://docs.oracle.com/javase/8/docs/api/
https://docs.oracle.com/en/java/
https://www.codecademy.com/resources/blog/advanced-java-code-challenges/
https://www.upgrad.com/blog/mvc-architecture-in-java/
https://www.devmedia.com.br/padrao-mvc-java-magazine/21995#11
https://www.devmedia.com.br/padrao-mvc-java-magazine/21995#5
https://www.edureka.co/blog/mvc-architecture-in-java/
https://www.devmedia.com.br/java-se-aprendendo-o-padrao-mvc/29546
https://www.azul.com/
https://start.spring.io/
https://www.fromdev.com/2014/10/most-widely-used-java-libraries.html
https://towardsdatascience.com/top-10-libraries-every-java-developer-should-know-37dd136dff54
https://medium.com/javarevisited/20-essential-java-libraries-and-apis-every-programmer-should-learn-5ccd41812fc7
https://dzone.com/articles/20-useful-open-source-libraries-for-java-programme
https://www.geeksforgeeks.org/arrays-in-java/
https://www.manualdaprogramacao.com.br/
https://howtodoinjava.com/
https://howtodoinjava.com/spring-boot2/testing/spring-boot-junit-resttemplate/
https://docs.oracle.com/en/
https://docs.oracle.com/en/java/javase/16/
https://www.javaguides.net/
https://www.javatpoint.com/
https://www.devmedia.com.br/qualidade-no-codigo-java-com-os-principios-s-o-l-i-
https://exercism.io/
http://www.universidadejava.com.br/
https://www.computersciencemaster.com.br/exercicios-de-orientacao-a-objetos/
https://www.azul.com/downloads/?package=jdk-fx
https://docs.oracle.com/javase/10/docs/api/overview-summary.html
https://www.caelum.com.br/apostila-java-web/
https://www.oracle.com/java/technologies/
https://dev.java/
https://www.oracle.com/java/technologies/downloads/#java17
https://docs.oracle.com/en/java/javase/17/
https://github.com/openjdk
https://openjdk.java.net/groups/build/doc/building.html
https://openjdk.java.net/
https://docs.oracle.com/javase/8/docs/api/java/util/package-summary.html
https://www.oracle.com/br/cloud
https://openjdk.java.net/projects/jdk/17/
http://sp16.datastructur.es/

HTML/CSS

https://materializecss.com/
https://monaca.io/
https://get.foundation/
https://www.w3tweaks.com/hand-picked-css-card-collections.html
http://www.flexboxdefense.com/
https://flexboxfroggy.com/
https://cssgridgarden.com/
https://flukeout.github.io/
https://rupl.github.io/unfold/
https://victordarras.fr/cssgame/
https://www.origamid.com/curso/css-flexbox/
https://www.origamid.com/curso/css-grid-layout/
https://www.origamid.com/projetos/css-grid-layout-guia-completo/
https://www.daniweb.com/programming/web-development/code/330933/a-simple-html-login-page-using-javascript
https://whatwg.org/

Noticias

https://medium.com/
https://dev.to/
https://www.itnews.com.au/
https://www.computerworld.com/news/
https://thehack.com.br/
https://tecnoblog.net/
https://diolinux.com.br/

https://www.manualdaprogramacao.com.br/
https://imasters.com.br/
https://news.ycombinator.com/
https://dl.acm.org/
https://www.computer.org/
https://ieeexplore.ieee.org/Xplore/home.jsp
https://www.elsevier.com/pt-br
https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en
Nova pasta

https://www.datasciencecentral.com/
https://www.dssgfellowship.org//blog/
https://www.datacamp.com/blog
https://www.becomingadatascientist.com/
https://www.codementor.io/community/topic/data-science
https://www.dataversity.net/category/blogs/
https://ischoolonline.berkeley.edu/blog/
https://www.dataplusscience.com/insights.html
https://nycdatascience.com/
https://ryanswanstrom.com/
https://online.datasciencedojo.com/blogs/
https://www.datarobot.com/blog/
https://blog.dominodatalab.com/

UX/UI

https://www.wallpaperflare.com/search?wallpaper=desktop
https://www.picpng.com/
https://www.gratispng.com/
http://www.pngpix.com/
https://pngtree.com/
https://br.freepik.com/
https://igluonline.com/pack-de-icones-png/#:~:text=%2022%20melhores%20packs%20de%20%C3%ADcones%20PNG%20e,Material%20Iconset%20vol%201%20(AI).%20%20More
https://wall.alphacoders.com/by_sub_category.php?id=209351&name=Attack+On+Titan+Wallpapers
https://www.pexels.com/pt-br/
https://isorepublic.com/
https://www.kaboompics.com/
https://www.everypixel.com/
https://handbrake.fr/
https://www.youtube.com/watch?v=vg-INqhKD5c&feature=youtu.be&ab_channel=GabrielSilvestri
https://www.figma.com/
https://www.colorzilla.com/
https://flatuicolors.com/
https://color.adobe.com/pt/create
https://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF
https://colorhunt.co/palettes
https://material.io/
https://www.canva.com/colors/color-palette-generator/
https://color.adobe.com/create/color-wheel
https://www.color-hex.com/
https://colordesigner.io/
https://mycolor.space/?hex=%23845EC2&sub=1
https://icons8.com/icons/set/.html
https://www.flaticon.com/free-icon/html-coding_13706
https://www.flaticon.com/
https://speckyboy.com/free-ui-interface-icon-set/
https://avocode.com/
https://emojipedia.org/
https://favicon.io/
https://iconarchive.com/search?q=html
https://google.github.io/material-design-icons/
https://br.placeit.net/
https://www.mockupworld.co/?s=T-SHIRT
http://www.matildefilmes.com.br/psicologia-das-cores-guia-avancado-para-profissionais/
https://neilpatel.com/br/blog/psicologia-das-cores-como-usar-cores-para-aumentar-sua-taxa-de-conversao/
https://color.adobe.com/pt/create/color-wheel
https://br.pinterest.com/
https://dribbble.com/
https://driwwwle.com/
https://milanote.com/
https://www.lapa.ninja/
https://www.behance.net/
https://dribbble.com/thatshutterboi
https://www.behance.net/thatshutterboi
https://www.darkmodedesign.com/
https://brasil.uxdesign.cc/keep-closet-um-estudo-sobre-decidir-o-que-vestir-fd86dd3b5bc
https://developers.google.com/web/fundamentals/design-and-ux/ux-basics
https://github.com/togiberlin/ui-ux-designer-roadmap
https://www.photopea.com/
https://sumo.app/

Ferramentas 

https://anyconv.com/pt/conversor-de-ai-para-jpeg/
https://www.pdfdrive.com/category/5
https://smallpdf.com/pdf-converter
https://www.freepdfconvert.com/pdf-to-word
https://www.freepdfconvert.com/
https://pt.z-lib.org/
https://sci-hub.scihubtw.tw/
https://www.beautiful.ai/
https://en.savefrom.net/19/
https://9convert.com/en4
https://www.virustotal.com/gui/
https://coggle.it/?org=0#YgJ7iUMks4i5b00G
https://answerthepublic.com/
https://whimsical.com/login
https://coggle.it/
https://miro.com/

**Comment by arthurspk** [comment]
Obrigado pela contribuição, vou organizar e commitar! 

Você também pode fazer um pull request seguindo os padrões do repositório para contribuição.

**Comment by DevEddi** [comment]
Já adicionei e um pull request, falta sua aprovação.
