### ISSUE TITLE
Remover o Índice 

### ISSUE THREAD

**Issue by acgtwentyone** [arthurspk/guiadevbrasil#117]
## Problema
Do meu ponto de vista, o conteúdo já é extenso, e o indice tambem o é dificultando a consulta de um determinado item.

## Solução
Removemos o indice do conteúdo, e adicionamos uma pequena informacao sobre como navegar no conteudo usando a navegacao padrao oferecida pelo github por padrao. Abaixo segue uma ilustracao. 

<img width="895" alt="Screen Shot 2022-04-15 at 10 35 52" src="https://user-images.githubusercontent.com/94224806/163566802-42b667ea-cf80-49e7-bd0f-46dc946b5038.png">

**Comment by arthurspk** [comment]
O índice não vai ser removido, se você não percebeu se você clicar em qualquer parte ali do indice ele vai te levar para a parte a qual ele está anexada, segundo ponto CTRL + F você acha qualquer coisa que precisa na página, o índice está no repositório para mostrar o que está presente nele.

**Comment by acgtwentyone** [comment]
Ok. Se fizer mais sentido, que assim seja. Embora acho que voce nao entendeu a minha sugestao.
