### ISSUE TITLE
Site Text Pop 3D  Fora do Ar

### ISSUE THREAD

**Issue by rodolforios** [arthurspk/guiadevbrasil#159]
O site text pop 3D não está mais no ar.

**Comment by Hopecanbereleased** [comment]
Hello can I know what going , why all people put thing on my phone

**Comment by Hopecanbereleased** [comment]
I don't know what happen. And some people say I abuse people . I just back from vacation ok

**Comment by Hopecanbereleased** [comment]
Which one show me

**Comment by nicoleeamoranto** [comment]
test

**Comment by tiredofbeingspiedon** [comment]
Idk who you are. I'm not a computer developer. I'm not even good at using a
computer. Don't know how to turn one on.

**Comment by Hopecanbereleased** [comment]
This is problem  i dont have computer or latpot
