### ISSUE TITLE
Certificações 

### ISSUE THREAD

**Issue by viniciusloma** [arthurspk/guiadevbrasil#163]
**Olá,**

Gostaria de deixar uma sugestão:

- Criar uma lista _(com links)_ com as melhores certificações grátis e pagas _(com valor aproximado)_  , haja vista que o mercado de trabalho valoriza muito algumas certificações.

**Gratidão 🙏🏻**

**Comment by arthurspk** [comment]
Será feito um guia de certificações para demais áreas da computação, seja você: desenvolvedor, arquiteto, ou profissional de segurança da informação!
