### ISSUE TITLE
Conteúdo de DevOps

### ISSUE THREAD

**Issue by pedrohdjs** [arthurspk/guiadevbrasil#192]
Oi, gente! Excelente trabalho com o repositório, muito conteúdo útil e relevante!

Uma sugestão que queria deixar é a inclusão de conteúdos sobre DevOps, Docker e Kubernetes.

Tenho pouco conhecimento sobre a área mas tem sido meu principal objeto de estudo recentemente, então acho que consigo abrir uma PR depois com um pouco de conteúdo que seja. :)

**Comment by Hnan9741** [comment]
[Uploading نص 2.txt…]()

**Comment by Leprachan444** [comment]
It’s wasn’t running a good program

**Comment by Aakashpandey123** [comment]
why do you feel this?

**Comment by HLAINGMYOOO** [comment]
good

**Comment by ghost** [comment]
![20230527_102103](https://github.com/arthurspk/guiadevbrasil/assets/115390179/17954b0e-4543-4195-8b48-95bb92c0cc93)

**Comment by ghost** [comment]
Forgot password that nillakashnillakash19@gmail.com

**Comment by ghost** [comment]
> why do you feel this?

Gmail password forgetting

**Comment by HLAINGMYOOO** [comment]
?

**Comment by Aeexis24** [comment]
> > why do you feel this?
> 
> Gmail password forgetting

Just can't remember
