### ISSUE TITLE
1520889698

### ISSUE THREAD

**Issue by Gimang01** [arthurspk/guiadevbrasil#205]
Heck akun free Fire

**Comment by Gimang01** [comment]
Saya ingin heck akun free Fire

**Comment by ghost** [comment]
Please help me i am forgetting my gmail password nillakashnillakash19@gmail.com Google always tel can't sine what i doing

**Comment by lonewolf101010** [comment]
you can download a key

**Comment by ghost** [comment]
![Screenshot_20230605_105948](https://github.com/arthurspk/guiadevbrasil/assets/115390179/b237857c-f98c-4315-bc1a-b2a205ccf812)
My gmail account password forgetting nillakashnillakash19@gmail.com pleacs any one help me. 
![20230527_102103](https://github.com/arthurspk/guiadevbrasil/assets/115390179/d24c3e33-fdf3-494d-b9b1-fd8fe82ca96e)
![20230527_032917](https://github.com/arthurspk/guiadevbrasil/assets/115390179/2592f185-2bec-4a91-9cd8-a0d8ecc109ef)
