### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by guieltorres** [arthurspk/guiadevbrasil#210]
Infelizmente Heroku não oferece mais planos gratuitos

**Comment by Hardhead-69** [comment]
[hY-fSWKBDhdOGQSAY&athwpid=0joshharriID4_1](www.instagram.com/joshharriD4_1I) 

> `IfukdherilbnHer4evrnever80```amswersyesimentfeardp@dlgaymanbhrdfan###OOBbalambImagoatnaMASTERBLEMEMBER!♾️https://github.com/lolnodikmurmslutnsuknmycock
/guiadevbrasil/issues/210#issue-1823130403
