### ISSUE TITLE
Adição para a categoria "Sites para estudar programação"

### ISSUE THREAD

**Issue by leaquis** [arthurspk/guiadevbrasil#212]
Recomendo adicionar o site Digital Innovation One (DIO) na categoria "Sites para estudar programação", pois a DIO oferece bootcamps gratuitos que ainda pode encaminhar as pessoas que concluem eles a tempo a uma vaga de emprego.

**Comment by Sultan1888** [comment]
> ننصحك بالتوصية بموقع Digital Innovation One (DIO) على فئة "Sites para estudar programação" ، وهي عبارة عن معسكرات تدريب في DIO oferece مجانية مثل pessoas que concluem eles a tempo a uma vaga de emprego.



> ننصحك بالتوصية بموقع Digital Innovation One (DIO) على فئة "Sites para estudar programação" ، وهي عبارة عن معسكرات تدريب في DIO oferece مجانية مثل pessoas que concluem eles a tempo a uma vaga de emprego.

👍

**Comment by Sultan1888** [comment]
> 

Ok good
