### ISSUE TITLE
Trilha dev

### ISSUE THREAD

**Issue by ismalevjr** [arthurspk/guiadevbrasil#235]

**Comment by Djoni-34** [comment]
Хорошо

**Comment by Djoni-34** [comment]
Исправим

**Comment by Findmycrypto** [comment]
[package 2.json](https://github.com/user-attachments/files/16116861/package.2.json)

**Comment by Findmycrypto** [comment]
My asset somehow after I bridged from base to ETHERIUM through MetaMask is now in its previous contract address and if only I could access code to reverse it to my address the miner sent to originally I can recover my maga trump 112 shares of it bought early End of March signed a message on 11th of April which I don’t understand where it went I tried too many maneuvering to get it back and need real help.
