### ISSUE TITLE
Plus

### ISSUE THREAD

**Issue by Renan-Olovics** [arthurspk/guiadevbrasil#3]
Extensão de navegadores para analisar tecnologias do site:
https://www.wappalyzer.com/

extensão para pegar a cor do site:
https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg

extensão para ver JSON pelo navegador:
https://github.com/tulios/json-viewer

extensão para quem trabalha com redux:
https://github.com/zalmoxisus/redux-devtools-extension

para quem usa windows com linux (WSL2)

wsl -l = list all distros 
wsl -t = turn off distro
wsl -d = turn on distro 
wsl -l --running  show running distros

Para quem trabalha com docker:

docker pull [ fazer download da imagem ]
docker run [ build and start a container, and print logs from it ]
docker build  [ build a container from a image ]
docker start -a  [ start a container ] ( -a flag = connect the STDIN and STDOUT )
docker stop  [ safe way to stop a container ]
docker kill  [ imediatly kill container ]

docker exec -it [ exec command inside the container ] ( -it flag = -i -t connect the STDIN and STDOUT )
docker logs  [ show logs from container ]
docker ps --all  [ show containers ] ( --all flag = todos os container )

docker system prune  [ clean docker delete everything ]

remover arquivos no linux:
rm -rf [ linux remove ] ( -rf = remove folder with everything )
cd .. volta uma pasta
cd [name] entra na pasta
ls lista todos arquivos da pasta

git:

git remote add [name(Git1)] [link(Github)]
git remote add [name(Git2)] [link(gitlab)]
git remote add [name(Git3)] [link(bitbucket)]

git add .
git commit [nome]
git push Git1 [sobe para o github]
git push Git2 [sobe para o gitlab]
git push Git3 [sobe para o bitbucket]

desse jeito voce pode ter o mesmo projeto em locais diferentes

colinha para SQL:
https://cdn.discordapp.com/attachments/719344822858547241/889907707820245002/1632221463353.png

instagram de dicas em react:
https://www.instagram.com/imateus.silva/
https://www.instagram.com/iuricode/

playlist must watch para entender javascript:
https://www.youtube.com/watch?v=j6iSONAO6sQ&list=PL9rc_FjKlX39T78CUANwmdta_d1CgUtMt&ab_channel=Origamid

metodos de array para js
https://cdn.discordapp.com/attachments/719344822858547241/875469062656905236/1628486570340.png

dica essencial de html:
https://www.instagram.com/p/CRzj2jdjUMV/

Foi isso que eu lembrei agora, recomendo voce organizar antes de subir alguma coisa kk

**Comment by arthurspk** [comment]
Obrigado de coração, vou organizar sim, pode deixar que em breve irei fazer o commit!

**Comment by jamiebryant94** [comment]
see se.   HEHE

**Comment by jamiebryant94** [comment]
lordy
