### ISSUE TITLE
Apps e jogos para treinar

### ISSUE THREAD

**Issue by joannaneves** [arthurspk/guiadevbrasil#54]
APPS:
Encode
Grasshopper

Jogos:
Code: https://code.org
Ruby warrior: https://github.com/ryanb/ruby-warrior
Codin Game: https://www.codingame.com/start
CodeGym: https://codegym.cc/
Elevator Saga: https://play.elevatorsaga.com/
Untrusted: https://alexnisnevich.github.io/untrusted/
Code & Conquer: https://www.codeandconquer.co/
CodeHunt: https://www.microsoft.com/en-us/research/project/code-hunt/
CodeWars: https://www.codewars.com/
CSSDiner : https://flukeout.github.io/
Flexbox froggy: https://flexboxfroggy.com/

**Comment by arthurspk** [comment]
Os links serão adicionados, obrigado por colaborar!
