### ISSUE TITLE
Adicionar o Scrimba

### ISSUE THREAD

**Issue by Miltonr87** [arthurspk/guiadevbrasil#64]
Fala meu conterrâneo, tudo blz? Não sei se a melhor forma de sugerir seria abrindo uma issue, mas vou fazer por aqui...

Como sugestão, inclui a plataforma da[ Scrimba](https://scrimba.com/) como IDE eletrônica e instituição de ensino. Eu uso a IDE da Scrimba pra testar situações com o React (tenho particulamente uma coleção de blocos de códigos na minha conta) ou mesmo pra participar de seleções de trabalho.

A Scrimba também disponibiliza diversos cursos gratuitos - quase 100% deles possuem como foco o Web Development. Se o inglês não for barreira pra pessoa, eu super indico pros novatos.

Grande abraço Arthur e parabéns pela ideia!

**Comment by revolut21** [comment]
> Fala meu conterrâneo, tudo blz? Não sei se a melhor forma de sugerir seria abrindo uma issue, mas vou fazer por aqui...
> 
> Como sugestão, inclui a plataforma da[ Scrimba](https://scrimba.com/) como IDE eletrônica e instituição de ensino. Eu uso a IDE da Scrimba pra testar situações com o React (tenho particulamente uma coleção de blocos de códigos na minha conta) ou mesmo pra participar de seleções de trabalho.
> 
> A Scrimba também disponibiliza diversos cursos gratuitos - quase 100% deles possuem como foco o Web Development. Se o inglês não for barreira pra pessoa, eu super indico pros novatos.
> 
> Grande abraço Arthur e parabéns pela ideia!

**Comment by arthurspk** [comment]
Obrigado pelo reconhecimento, a informações serão adicionadas! 😄
