### ISSUE TITLE
Conteúdo de Java

### ISSUE THREAD

**Issue by DevEddi** [arthurspk/guiadevbrasil#66]
Sou um fã da linguagem Java, vi que tem pouco conteúdo. Logo envio mais links úteis.

Java Documentação - [Docs Java](https://docs.oracle.com/en/java/)
Download Azul OpenJDK - [JDK-JAVA](https://www.azul.com/downloads/?package=jdk-fxl)

**Comment by glendasabinoo** [comment]
Aproveitando para repassar o melhor curso de Java que já vi, com muitos exercícios e uma didática sensacional:

[Loiane training - curso Java básico](https://loiane.training/curso/java-basico)

**Comment by arthurspk** [comment]
Ambos serão adicionados, obrigado pela colaboração.
