### ISSUE TITLE
Sugestões de adição de Curso de Dart e Flutter atualizado e de canal com conteúdo gratuito

### ISSUE THREAD

**Issue by tauamendonca** [arthurspk/guiadevbrasil#68]
Sugestões para a parte de cursos gratuitos:
Curso de Flutter atualizado da Flutterando (2022) - https://www.youtube.com/playlist?list=PLlBnICoI-g-fuy5jZiCufhFip1BlBswI7
Curso de programação com Dart (canal Deivid Willyam) - https://www.youtube.com/playlist?list=PLRpTFz5_57cseSiszvssXO7HKVzOsrI77

O canal do Deivid Willyam tem diversos conteúdos úteis para os devs de Dart e Flutter

**Comment by arthurspk** [comment]
Será adicionado.
