### ISSUE TITLE
Excelente trabalho

### ISSUE THREAD

**Issue by ribafs** [arthurspk/guiadevbrasil#82]
Muito agradecido.

Apenas venho sugerir que o melhor canal de programação apareça na lista:

Canal do João Ribeiro

**Comment by JonathasGit** [comment]
Parabéns pelo trabalho, vou usar essa lista muito ainda.

**Comment by Donnadam** [comment]
I don't believe I am still getting these emails??.
Unless I am the Subject. I  unsubscribed laste year & only subscribe for
1/2 weeks.
How can I still be in this thread.
***@***.*** ***@***.***> *

Donna Murdoch

**Comment by FelipeFama** [comment]
Muito obrigado por criarem esse repositório.

**Comment by arthurspk** [comment]
Agradeço a todos pelo reconhecimento! 😄
